# Name of the agent to add to the system.
string agent_id
# List of tasks the agent is able to perform.
string[] tasks
# (Optional) Define if the agent should be registered for task allocation.
bool register
---
# State of result (0=fail,1=success)
bool success
# Success or failure details
string msg