# Name of the robot to add to the system.
string robot_id
# List of tasks the robot is able to perform.
string[] tasks
# (Optional) Define if the robot should be registered for task allocation.
bool register
---
# Return:
# 0 : success
# 1 : robot not admissible
# 2 : tasks not in list
# 3 : robot already connected
# 4 : no base stations available
uint8 success