# Name of the robot to unregister from the system.
string robot_id
# Action of robot when disconnected ("stop", "finish_task", "return_to_base")
string action
---
# Return:
# 0 : success
# 1 : robot not registered
# 2 : already set to unregister on task completion
uint8 success
