modules:
  - name: navigation
    role: virtual_robot
  - name: rasberry_health_monitoring
    role: robot
  - name: rasberry_transportation
    role: field_courier
navigation_properties:
    has_presence: true
    restrictions: inter-row
module_properties:
    max_load: 2
visualisation_properties:
    structure_type: short
    rviz_model: short_robot
