modules:
  - name: base
    role: human #virtual_human
  - name: rasberry_transportation
    role: picker
navigation_properties:
    has_presence: false
visualisation_properties:
    rviz_model: human
