modules:
  - name: base
    interface: LocalisedHuman
    details:
      - rviz_model: human

  - name: navigation
    interface: Human
    details:
      - has_presence: false
      - restrictions: short

  - name: rasberry_transportation_pkg
    interface: Picker
    details:
      - state_listener: /car_client/get_states_kv
      - state_publisher: /car_client/set_states_kv

