modules:
  - name: base
    role: VirtualHuman
    details:
      - rviz_model: human

  - name: navigation
    role: Human
    details:
      - has_presence: false
      - restrictions: short

  - name: rasberry_transportation_pkg
    role: Picker
