modules:
  - name: base
    role: Empty
    details:
      - rviz_model: human

  - name: navigation
    role: Empty
    details:
      - has_presence: false

  - name: assignment
    role: SchedulerManager

  - name: rasberry_data_collection_pkg
    role: Scheduler

  - name: rasberry_health_monitoring_pkg
    role: Scheduler

