modules:
  - name: base
    interface: Empty
    details:
      - rviz_model: human

  - name: navigation
    interface: Empty
    details:
      - has_presence: false

  - name: assignment
    interface: SchedulerManager

  - name: rasberry_data_collection_pkg
    interface: Scheduler

  - name: rasberry_health_monitoring_pkg
    interface: Scheduler

