modules:
  - name: base
    interface: Robot
    details:
      - structure_type: short
      - rviz_model: short_robot
      - rviz_location_topic: ~robot_pose
      - rviz_location_attach: True

  - name: navigation
    interface: RobotDebug
    details:
      - has_presence: true
      - restrictions: short
      - wait_node_name: base_tp_node

  - name: rasberry_health_monitoring_pkg
    interface: Robot

  - name: rasberry_transportation_pkg
    interface: Robot
    details:
      - max_load: 1
