modules:
  - name: base
    role: robot
  - name: health_monitoring
    role: robot
  - name: transportation
    role: field_courier
navigation_properties:
    has_presence: true
    restrictions: short
    #map_filters:
    #  - only_restricitons
    #  - no_nodes_with_presence
module_properties:
    max_load: 1
visualisation_properties:
    structure_type: short
    rviz_model: short_robot
