modules:
  - name: base
    interface: Robot
    details:
      - structure_type: short
      - rviz:
            structure: 'short_transportation'
            colour: 'blue'
            tf_source_topic: '~robot_pose'
            tf_source_type: 'geometry_msgs/Pose'

  - name: navigation
    interface: RobotDebug
    details:
      - has_presence: true
      - restrictions: short
      - occupation:
            r-c: ['self', 'neighbour_row_tall_ends']
            dock-: ['self', 'entry']
      - wait_node_name: base_tp_node

  - name: rasberry_health_monitoring_pkg
    interface: Robot

  - name: rasberry_transportation_pkg
    interface: Robot
    details:
      - max_load: 1
