modules:
  - name: base
    interface: LocalisedHuman
    details:
      - rviz_model: special_node
      - rviz_location_topic: ~robot_pose
      - rviz_location_attach: True

  - name: navigation
    interface: Human
    details:
      - has_presence: false

  - name: rasberry_transportation_pkg
    interface: Storage
    details:
      - state_subscriber: /car_client/get_states_kv
      - state_publisher: /car_client/set_states_kv
