modules:
  - name: base
    role: virtual_robot
  - name: rasberry_health_monitoring
    role: robot
  - name: rasberry_uv_treatment
    role: phototherapist
  - name: rasberry_data_collection
    role: scanner
navigation_properties:
    restrictions: intra-row
    has_presence: true
visualisation_properties:
    structure_type: tall
    rviz_model: tall_robot
