modules:
  - name: base
    interface: Robot
    details:
      - structure_type: tall
      - rviz_model: tall_robot

  - name: navigation
    interface: RobotDebug
    details:
      - has_presence: true
      - restrictions: tall
      - wait_node_name: base_dc_node

  - name: rasberry_health_monitoring_pkg
    interface: RobotDebug

  - name: rasberry_data_collection_pkg
    interface: ScannerDebug
