modules:
  - name: base
    role: robot
  - name: health_monitoring
    role: robot
  - name: data_collection
    role: scanner
navigation_properties:
    restrictions: tall
    has_presence: true
    wait_node_name: base_dc_node
    #map_filters:
    #  - only_restrictions
    #  - no_rows_with_presence
visualisation_properties:
    structure_type: tall
    rviz_model: tall_robot
