modules:
  - name: base
    interface: Robot
    details:
      - structure_type: tall
      - rviz:
            structure: 'tall_data_collection'
            colour: 'blue'
            tf_source_topic: '~robot_pose'
            tf_source_type: 'geometry_msgs/Pose'

  - name: navigation
    interface: Robot
    details:
      - has_presence: true
      - restrictions: tall
      - wait_node_name: base_dc_node

  - name: rasberry_health_monitoring_pkg
    interface: Robot

  - name: rasberry_data_collection_pkg
    interface: Scanner
