modules:
  - name: base
    role: robot
  - name: rasberry_health_monitoring
    role: robot
  #- name: rasberry_uv_treatment
  #  role: phototherapist
  - name: rasberry_data_collection
    role: scanner
navigation_properties:
    restrictions: tall
    has_presence: true
    #map_filters:
    #  - only_restrictions
    #  - no_rows_with_presence
visualisation_properties:
    structure_type: tall
    rviz_model: tall_robot
