modules:
  - name: base
    interface: Robot
    details:
      - structure_type: tall
      - rviz_model: tall_robot
      - rviz:
            structure: 'tall_robot'
            colour: 'black'
            tf_source_topic: '~robot_pose'
            tf_source_type: 'geometry_msgs/Pose'


  - name: navigation
    interface: RobotDebug
    details:
      - has_presence: true
      - restrictions: tall
      - wait_node_name: base_dc_node

  - name: rasberry_health_monitoring_pkg
    interface: RobotDebug

  - name: rasberry_data_collection_pkg
    interface: ScannerDebug
