modules:
  - name: base
    role: VirtualRobot
    details:
      - structure_type: tall
      - rviz_model: tall_robot

  - name: navigation
    role: Robot
    details:
      - has_presence: true
      - restrictions: tall

  - name: rasberry_health_monitoring_pkg
    role: Robot

  #- name: rasberry_uv_treatment
  #  role: Phototherapist

  - name: rasberry_data_collection
    role: Scanner
