modules:
  - name: base
    role: robot
  - name: health_monitoring
    role: robot
  - name: uv_treatment
    role: phototherapist
  - name: data_collection
    role: scanner
navigation_properties:
    restrictions: intra-row
    has_presence: true
    #map_filters:
    #  - only_restrictions
    #  - no_rows_with_presence
visualisation_properties:
    structure_type: tall
    rviz_model: tall_robot
