modules:
  - name: base
    role: Robot
    details:
      - structure_type: tall
      - rviz_model: tall_robot

  - name: navigation
    role: RobotDebug
    details:
      - has_presence: true
      - restrictions: tall
      - wait_node_name: base_dc_node

  - name: rasberry_health_monitoring_pkg
    role: RobotDebug

  - name: rasberry_data_collection_pkg
    role: ScannerDebug
